tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "microsoft/git"

brew "openssl@1.1"
brew "sqlite"
brew "awscli"
brew "curl"
brew "fontforge"
brew "git"
brew "go"
brew "grep"
brew "jq"
brew "macvim"
brew "markdown"
brew "mas"
brew "mysql", restart_service: true
brew "nginx", restart_service: true
brew "node@16"
brew "openjdk"
brew "peco"
brew "plenv"
brew "reattach-to-user-namespace"
brew "subversion"
brew "telnet"
brew "tmux"
brew "wget"
brew "zsh"
brew "font-ricty-diminished"
cask "appcleaner"
cask "docker"
cask "git-credential-manager-core"
cask "google-chrome"
cask "iterm2"
cask "keepassx"
cask "logitech-options"
cask "rocket-chat"
cask "skitch"
cask "the-unarchiver"
cask "thunderbird"
cask "toggl-track"
cask "visual-studio-code"
cask "xmind"
cask "zoom"

#mas "Keynote", id: 409183694
#mas "Mobility", id: 1097637587
#mas "Numbers", id: 409203825
#mas "Pages", id: 409201541
#mas "Todoist", id: 585829637
#mas "Xcode", id: 497799835
